### ISSUE TITLE
AssignmentB_16

### ISSUE THREAD

**Issue by tokkiboi** [tokkiboi/Perl#2]
@borgified 
need help w/ calculating SUM of user input string;
without using regex or array -_____-

**Comment by borgified** [comment]
i think ur answer is using some regex and array (when you use split)

**Comment by borgified** [comment]
@tokkiboi hows it going so far still stuck?

**Comment by tokkiboi** [comment]
haha.. apparently was too ahead with assignment.. we covered some that
could be used tonight.. so ill try update tommorw ^^

**Comment by tokkiboi** [comment]
@borgified hm.. i think i spent last 8 hours looking online and ur code.  and no, we did like first 2 chapters, and just finished scalar and array yesterday..

I was actually trying to do this way: and like just add conditional statements.
But without using regex, i dunno how i can check if the variable is numeric or character.
$_ =~ /\D/     <--- ii can't use that right?  oh regular expression and pattern matching is same thing right/ ^^

print "Enter a sequence of numbers from 1 to 20\n";
$sum=0;
while (1){
chomp($input=<>);
for ($i=0;$i < length($input);$i++){
$char=substr($input,$i,length($i)+1);
$sum+=$char;
print $sum;
print "\n";
}
}

ASERIOAUSDGT*WE(%&( i'll try working on it after short break..

**Comment by tokkiboi** [comment]
@borgified hm.. what a foobar class.. nowhere online has anything that can be used, unless dealing with higher level programming skills o_O...
i tried scratching off everything and start from up top by just trying to get the list of chars and concatenated with + signs and printing the sum of all #s, regardless the conditions..
especially can't get the 2-digit input to be recognized as one integer variable..
**repeat** **delete** **try different thing**.. and now i confused myself further hahahah..

print "input a string:\t";
chomp($string=<>);
while ($string ne undef){
$sum=0;
$chars;
$position=0;
$offset=0;
for ($position=0; $position<length($string);$position++){
$offset=length($string);
$chars=substr($string,$position,$offset);
print "Current input character is\t$chars\n";  ##print value of variable input
print "Length of the $chars is ";
print length($chars),"\n";
$position++;
$position=length($chars)+1;
$sum+=$sum + $chars;
print $sum;
}
#$chars=int $chars;
print "$sum\n";
}
#print $sum,"\n";
#print $sum,"\n";
# print hyphenate($chars); # "e-x-t-e-r-m-i-n-a-t-e"
# }
# sub hyphenate {
  # # Extract the first argument from the array, ignore everything else
  # my $word = shift @_;
  # # An overly clever list comprehension
  # $word = join "+", map { substr $word, $_, length $_ } (0 .. (length $word) - 1);
  # return $word;
# }
#for(my $x=0;$x<$length;$x++){
    #my $cursor = substr $str,$x,1; #extract the char at location $x

**Comment by borgified** [comment]
see https://guides.github.com/features/mastering-markdown/ for formatting the text you write here

for code use ``` at the beginning and at the end. looks like this:
```
print "hello world";
```

i looked over what you wrote and it doesnt seem to answer what is required by the assignment are you still doing B16 or are you on a different assignment?

the code i have actually runs, so you can download it to your computer and just run it to see what is going on. i can walk you through it too if you need.

**Comment by tokkiboi** [comment]
ah.. i was looking for such feature.. thnx.. so many were stumped, we got extension, so i was trying to start from scratch and understand babysteps

**Comment by borgified** [comment]
ok i see. babysteps are good, thats why in my script i did exactly that. thats the whole point of the cursor variable. it iterates over every character and decides what to do depending on what it is seeing.

**Comment by tokkiboi** [comment]
i will see if i can update with what i am struggling.. currently studying
for 2 exams and 1 c++ program.

funkiest part is
1) trying to two bit element like 12 [but read as 1 and 2 separately
concatenated as a single number.
2) printing all numbers until it hits q or Q, then i just chop off all the
inea that follow... without using array of course..
3)  keep getting error about comparison done is not numeric... however i
try  like > for numeric  or gt for string..

i will try updating it with Qs hopefully for u to see what i mean.. thnx!

**Comment by tokkiboi** [comment]
@borgified hm.. my baby steps are like below.. removed all and restarted with at least getting the input and line correctly with their sum...

```
 #!/usr/bin/perl
no strict ;
use warnings ;
#while ($input ne ''){
 print "Please enter a sequence of numbers between 1 and 20 to get their sum:\t";
$counter=0;
$sum=0;
$/=" ";
  while (<DATA>){
    chomp($_);
     $sum+=$_;
     	$counter++;
	print "Currently read: \n";
	print $_,"";
	print "Current sum: \n";
		print $sum,"\n";
	if (lc($_) eq 'q') {
         last;}else{next;}
               	 if (is_a_valid_number($num)){
                     next;}
               else{
                 print "Please input numbers between 1 and 20 only";
                redo; }
                #print "$_\n$sum\n";
              #}
              #print "\n";
#            }
              $sum+=$_;
              print $_,$sum,"\n";
                            }
          exit;
sub is_a_valid_number {
  $num = shift @_;
  if(($num >= 1)||($num <= 20)){
    $sum=$sum+$num;
    return 1;
  }else{
    return 0;
 }
 }
__DATA__
1 12 a 2 5 P Q
```
