### ISSUE TITLE
how can I pipe awk?

### ISSUE THREAD

**Issue by tokkiboi** [tokkiboi/Perl#4]
@borgified trying to take 2 arguments as directories, 3rd argument as output file, but keep getting syntax error when piping "awk" command

## write a program that takes any number of directory names as command line arguments and an output filename as a last argument. The program checks that there are at least 2 command line arguments, at least one directory name and one output file name

#!/usr/bin/perl -w
if ($#ARGV != 2 ) {
        print "usage: script dir1 dir2 filename\n";
        exit;
}
$dir1=$ARGV[0];
$dir2=$ARGV[1];
$filename=$ARGV[2];
if ( -d $ARGV[0]) {
        $dir1 = system ("ls -al $dir1|awk '{b+=$5}END{print b}'");  ## <-- $5
}
if ( -d $ARGV[1]){
        $dir2 = system ("ls -al $dir2|awk '{b+=$5}END{print b}'");
}
#print $dir1,"\n";
#print $dir2,"\n";

**Comment by borgified** [comment]
not sure why you have awk in there, seems unecessary

but basically the idea is that you are reading the @ARGV
the requirement is that the size of this array must be at least 2 (hint:
just check the size of the @ARGV array)

u can pop the last item of the @ARGV array and take that as your output
filename. then u can iterate over the @ARGV array in a foreach loop to go
through each of the directory arguments.

this is all solved in perl, no awk required!

lemme know if you need more hints

**Comment by tokkiboi** [comment]
not quite sure if i am following what you are hinting at.
The actual trouble I was having was the part where.. listing the directory and outputting the total size of the contents in the directory to the output file...

like in regular terminal i can list the directory and grab the 5th column which displays the size of all contents as follow:
bobo@bobo /cygdrive/c/GitHub/perl
$ ls -al | awk '{b+=$5}END{print b}'
11422004
bobo@bobo /cygdrive/c/GitHub/perl
$ ls -al | awk '{b+=$5}END{print b}' && ls -al ../ | awk '{b+=$5}END {print b}'
11422004
0

I was curious why awk wasn't working through piping via perl script.. it would just syntax error at $5 when I am trying to grab the 5th column items from 'ls -al'

**Comment by tokkiboi** [comment]
actually i guess glob works better in this sense

$ cat test.pl
#!/usr/bin/perl -w
if ($#ARGV < 2 ) {
        print "usage: script dir1 dir2 filename\n";
        exit;
}
$dir1=$ARGV[0];
$dir2=$ARGV[1];
$filename=$ARGV[2];
$size=0;
$size2=0;
if ( -d $ARGV[0]){
for (glob("$dir1/*")){
$size+= -s $_;
print $size,"\n";}
#       system ("awk '{b+=$5}END{print b}' (ls -al $dir1)");
}
if ( -d $ARGV[1]){
for (glob("$dir2/*")){
$size2+= -s $_;
print $size2,"\n";}}

**Comment by tokkiboi** [comment]
nvm fixed and done.. i misused(didn't use) escape chars properly
